<?php
session_start();
include 'config/db.php';
include 'includes/header.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: login.php");
    exit();
}

// 1. Current Date Reference
$today = date('Y-m-d');
$this_month = date('m');
$this_year = date('Y');

// 2. Fetch Admissions with Bed Prices and Lab Fees
// This ensures we get every component of your bill summary
$sql = "SELECT 
            a.admission_id, a.admission_date, a.discharge_date, a.status, a.admission_fee,
            b.price_per_day,
            (SELECT COALESCE(SUM(test_fees), 0) FROM lab_tests WHERE admission_id = a.admission_id) as lab_total
        FROM admissions a
        JOIN beds b ON a.bed_id = b.bed_id";

$result = $conn->query($sql);

$daily_total = 0; $monthly_total = 0; $yearly_total = 0;

if ($result && $result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        
        // --- LOGIC: DURATION CALCULATION ---
        $start = new DateTime($row['admission_date']);
        
        // Use discharge_date if finished, otherwise use 'today' for ongoing patients
        $end = ($row['status'] == 'Discharged' && !empty($row['discharge_date'])) 
               ? new DateTime($row['discharge_date']) 
               : new DateTime();

        $diff = $start->diff($end);
        $days = ($diff->days > 0) ? $diff->days : 1; // Minimum 1 day charge as per image_70e4ff.png

        // --- LOGIC: BILL COMPONENTS (Based on your screenshots) ---
        $bed_charges = $days * (float)$row['price_per_day'];
        $consultation = 500; // Fixed Service Fee seen in image_70e4ff.png
        $admission_fee = (float)$row['admission_fee']; // Standard 2000 TK
        $lab_fees = (float)$row['lab_total'];

        // Total Revenue for this specific admission
        $patient_revenue = $bed_charges + $consultation + $admission_fee + $lab_fees;

        // --- LOGIC: TIME-BASED ACCUMULATION ---
        $adm_year = $start->format('Y');
        $adm_month = $start->format('m');
        $adm_day = $start->format('Y-m-d');

        // Yearly: All revenue generated by admissions starting this year
        if ($adm_year == $this_year) {
            $yearly_total += $patient_revenue;
        }

        // Monthly: All revenue generated by admissions starting this month
        if ($adm_year == $this_year && $adm_month == $this_month) {
            $monthly_total += $patient_revenue;
        }

        // Daily: Revenue attributed specifically to TODAY
        if ($adm_day == $today) {
            // New admissions today contribute their full startup bill
            $daily_total += $patient_revenue;
        } elseif ($row['status'] == 'Admitted') {
            // Ongoing patients contribute just today's Bed + Service fee to the daily total
            $daily_total += (float)$row['price_per_day'] + 500;
        }
    }
}
?>

<div class="container my-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="fw-bold">Financial Revenue Report</h2>
        <a href="admin_dashboard.php" class="btn btn-dark btn-sm shadow-sm">Back</a>
    </div>

    <div class="row g-4 text-center">
        <div class="col-md-4">
            <div class="card border-0 shadow-sm bg-primary text-white p-4">
                <h6 class="small text-uppercase">Today's Revenue</h6>
                <h2 class="fw-bold">TK <?= number_format($daily_total, 2) ?></h2>
                <small>New admissions + daily rates</small>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card border-0 shadow-sm bg-success text-white p-4">
                <h6 class="small text-uppercase">Monthly (<?= date('F') ?>)</h6>
                <h2 class="fw-bold">TK <?= number_format($monthly_total, 2) ?></h2>
                <small>Total accrued this month</small>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card border-0 shadow-sm bg-dark text-white p-4">
                <h6 class="small text-uppercase">Yearly Revenue (<?= $this_year ?>)</h6>
                <h2 class="fw-bold">TK <?= number_format($yearly_total, 2) ?></h2>
                <small>Total fiscal performance</small>
            </div>
        </div>
    </div>
</div>

<?php include 'includes/footer.php'; ?>